version: "3.9"

services:
  db:
    image: postgres:14
    container_name: booking_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: booking
    ports:
      - "5432:5432"
    volumes:
      - ./db/seedfile.sql:/docker-entrypoint-initdb.d/seed.sql

  api:
    build: .
    container_name: booking_api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: booking
      JWT_SECRET: riseAPI
