version: '3.8'
#docker-compose.yml for the seed file
# This file is used to set up a PostgreSQL database with a seed file for initial data
services:
  db:
    image: postgres:14
    container_name: booking_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: booking
    ports:
      - "5432:5432"
    volumes:
      - ./db/seedfile.sql:/docker-entrypoint-initdb.d/seed.sql
